### ISSUE TITLE
Support for FireFox

### ISSUE THREAD

**Issue by CB49** [mnxn/firefox-refreshUI#1]
![image](https://user-images.githubusercontent.com/25035681/41243578-585f52ce-6d57-11e8-9a5e-2a47ba12d077.png)
I saw your css and i thought it looked great. i was wondering if you can get this to work on firefox. as u can see, it doesnt work. thx

**Comment by mnxn** [comment]
It looks like you're using a pre-quantum firefox version. I will not being providing support for it.

Please update to the latest version, preferably the developer edition: https://www.mozilla.org/en-US/firefox/developer/

**Comment by CB49** [comment]
i heard using the developer edition could get me hacked or something. is it safe?

**Comment by mnxn** [comment]
It's safe, the download is directly from Mozilla.
